type FieldState = {theme:ThemeId;accent:string;progress:number|null;active:boolean;map:number[];gpu:number|null};
class SignalField {
 private canvas:HTMLCanvasElement;private context:CanvasRenderingContext2D;private state:()=>FieldState;private observer:ResizeObserver;private width=1;private height=1;private frame=0;private last=0;private reduced=matchMedia('(prefers-reduced-motion: reduce)');private dead=false;
 constructor(canvas:HTMLCanvasElement,state:()=>FieldState){this.canvas=canvas;this.context=canvas.getContext('2d',{alpha:true})!;this.state=state;this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);this.resize();this.loop(0)}
 private resize(){const rect=this.canvas.getBoundingClientRect();this.width=Math.max(1,rect.width);this.height=Math.max(1,rect.height);const dpr=Math.min(devicePixelRatio,1.5);this.canvas.width=this.width*dpr;this.canvas.height=this.height*dpr;this.context.setTransform(dpr,0,0,dpr,0,0)}
 private loop=(now:number)=>{if(this.dead)return;this.frame=requestAnimationFrame(this.loop);if(document.hidden||now-this.last<(this.reduced.matches?950:1000/30))return;this.last=now;this.draw(this.reduced.matches?0:now/1000)};
 private draw(time:number){const {theme,accent,progress,active,map,gpu}=this.state(),ctx=this.context,w=this.width,h=this.height;ctx.clearRect(0,0,w,h);const paper=theme==='paper',signal=theme==='signal';const phase=active?time*.28:time*.045;const fraction=progress==null?.38:progress/100;const rows=paper?19:signal?30:26;const cols=signal?53:48;const tint=paper?'#817e72':signal?'#a5a0ba':'#758078';const left=w*.04,right=w*.97;ctx.lineCap=paper?'butt':'round';for(let row=0;row<rows;row++){const rowFrac=row/(rows-1);ctx.beginPath();let points:{x:number;y:number;processed:boolean;size:number}[]=[];for(let col=0;col<cols;col++){const t=col/(cols-1);const data=map.length?map[Math.min(map.length-1,Math.floor(t*map.length))]:.52;const envelope=Math.pow(Math.sin(t*Math.PI),.75);const warp=Math.sin(t*6.3+rowFrac*3+phase)*Math.sin(rowFrac*Math.PI);const fold=Math.cos(t*4.8-rowFrac*4.2+phase*.4);const x=left+(right-left)*t+Math.sin(rowFrac*3.3+t*4+phase*.2)*w*.025;const y=h*.5+(rowFrac-.5)*h*.49+envelope*(warp*h*.145+fold*h*.06)*(0.65+data*.35);const processed=t<fraction;const size=paper?1.05:signal?(1.05+envelope*1.05):.95;points.push({x,y,processed,size});if(col===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.strokeStyle=tint;ctx.globalAlpha=paper?.19:signal?.12:.19;ctx.lineWidth=paper?.55:.65;ctx.stroke();for(const p of points){ctx.fillStyle=p.processed?accent:tint;ctx.globalAlpha=p.processed?.9:.5;if(paper){ctx.fillRect(p.x,p.y,2.3,1)}else{ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}}}
 if(signal){ctx.globalAlpha=.1;ctx.strokeStyle=accent;ctx.lineWidth=1;for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(w*.5,h*.53,w*(.24+i*.06),h*(.26+i*.01),-.23,0,Math.PI*2);ctx.stroke()}}
 ctx.globalAlpha=1;if(active&&progress!==null){const x=left+(right-left)*fraction;ctx.strokeStyle=accent;ctx.globalAlpha=.3;ctx.setLineDash([2,6]);ctx.beginPath();ctx.moveTo(x,h*.18);ctx.lineTo(x,h*.83);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.fillStyle=accent;ctx.fillRect(x-2,h*.83,4,4)}
 }
 destroy(){this.dead=true;cancelAnimationFrame(this.frame);this.observer.disconnect()}
}
